services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bookstore-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=bookstore_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d bookstore_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookstore-network

volumes:
  postgres_data:

networks:
  bookstore-network:
    driver: bridge